name: flutter_projects
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  animate_do: ^2.1.0
  flutter_rating_bar: ^4.0.0
  encrypt: ^5.0.1
  flutter_secure_storage: ^5.0.2
  fluttertoast: ^8.0.9
  google_fonts: ^2.3.1
  hive: ^2.0.6
  hive_flutter: ^1.1.0
  local_auth: ^1.1.11
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - Assets/
    - Assets/coffee/
    - Assets/list-animated/
    - Assets/ui/day-01/
    - Assets/ui/day-02/
    - Assets/ui/day-03/
    - Assets/cinema/
    - Assets/scrollable/
    - Assets/food/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
